import Head from 'next/head';
// import styles from '../styles/Home.module.css';
import { replies } from '../data';
import { useState } from 'react';

export default function Home() {

  const [cookieStand, setCookieStand] = useState("Report Table Coming Soon...");

  function formHandler(event) {
    event.preventDefault();

    let cookieStand = {
      location: event.target.elements.location.value,
      minCust: event.target.elements.minCust.value,
      maxCust: event.target.elements.maxCust.value,
      avgCookies: event.target.elements.avgCookies.value
    }

    setCookieStand(JSON.stringify(cookieStand))
  }

  return (
    <div className="">
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex items-center justify-between p-4 bg-green-500 text-gray-50">
        <h1 className="text-4xl text-black">Cookie Stand Admin</h1>
      </header>

      <main className="w-3/4 mx-auto">

        <div className="m-4 bg-green-300 rounded-md">

          <form onSubmit={formHandler} className="flex flex-col">
            <h2 className="text-3xl text-center rounded-t-md">Create Cookie Stand</h2>

            <div className="flex p-2">
              <label className="pr-2 pl-2">Location </label>
              <input name="location" className="grow" />
            </div>

            <div className="flex flex-row p-2">

              <div className="p-2 flex flex-col w-1/4">
                <label>Minimum Customers per Hour</label>
                <input name="minCust" className="flex-auto pl-1" />
              </div>

              <div className="p-2 flex flex-col w-1/4">
                <label>Maximum Customers per Hour</label>
                <input name="maxCust" className="flex-auto pl-1" />
              </div>

              <div className="p-2 flex flex-col w-1/4">
                <label>Average Cookies per Sale</label>
                <input name="avgCookies" className="flex-auto pl-1" />
              </div>

              <button className="p-2 bg-green-600 text-black w-1/4 grow">Create</button>

            </div>

          </form>
        </div>

        <p className="m-4 text-center">{cookieStand}</p>

      </main>

      <footer className="p-3 bg-green-500 text-gray-50">
        <p className="text-black">&copy;2023</p>
      </footer>
    </div>
  );
}
