import Head from 'next/head';
import Header from '../components/Header';
import Main from '../components/Main';
import Footer from '../components/Footer';
import ReportTable from '../components/ReportTable';
// import styles from '../styles/Home.module.css';
import { replies } from '../data';
import { useEffect, useState } from 'react';
import { cookies } from 'next/dist/client/components/headers';

export default function CookieStandAdmin() {
  const [cookieStands, setCookieStands] = useState([]);
  const [grandTotal, setGrandTotal] = useState([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]);
  // const hours = ['6am', '7am', '8am', '9am', '10am', '11am', '12pm', '1pm', '2pm', '3pm', '4pm', '5pm', '6pm', '7pm'];



  useEffect((event) => {
    // Calculate total of all stores
    let array = [];
    let subtotal = 0;

    for (let i = 0; i < 15; i++) {
      subtotal = 0;

      cookieStands.forEach((stand) => {
        subtotal += stand.salesArray[i]
      })

      array.push(subtotal);
    }

    // Save new store to state
    setGrandTotal(array);

  }, [cookieStands])

  function formHandler(event) {
    event.preventDefault();

    let location = event.target.elements.location.value;
    let minCust = event.target.elements.minCust.value;
    let maxCust = event.target.elements.maxCust.value;
    let avgCookies = event.target.elements.avgCookies.value;

    // Create new store
    let newStoreSalesArray = calcSales(parseFloat(minCust), parseFloat(maxCust), parseFloat(avgCookies));

    let newCookieStand = {
      location: location,
      minCust: minCust,
      maxCust: maxCust,
      avgCookies: avgCookies,
      salesArray: newStoreSalesArray,
    }

    setCookieStands([...cookieStands, newCookieStand])

    event.target.reset();
  }

  function calcSales(minCust, maxCust, avgCookies) {
    let array = [];

    for (let i = 0; i < 14; i++) {
      array[i] = Math.round(Math.round(Math.floor(Math.random() * (maxCust - minCust + 1) + minCust)) * avgCookies)
    }

    // Calculate total
    let total = 0;

    array.forEach(item => {
      total += item;
    })

    array.push(total)

    return array
  }

  function calcStoreTotal(salesArray) {
    let total = 0;

    salesArray.forEach(item => {
      total += item;
    })

    return total
  }


  return (
    <div className="">
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      <Main 
        formHandler = {formHandler}
        cookieStands = {cookieStands}
        grandTotal = {grandTotal}
      
      />

      <Footer
        cookieStands={cookieStands}

      />

    </div>
  );
}
